on: workflow_dispatch

name: Azure CLI start ssh tunnel - after build and delpoy

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CLI }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: echo "STARTUP TUNNEL" && autossh -L 4002:localhost:3306 -N -i /home/.ssh/id_rsa gnminadmin@nextgenanz04.eastus2.cloudapp.azure.com -4 -o "StrictHostKeyChecking no" -M
          az account show
          az storage -h
